/* tslint:disable */
/* eslint-disable */
/**
 * merkle-tree
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
/**
 * MerkleTreeApi - axios parameter creator
 * @export
 */
export const MerkleTreeApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary /path/:leafIndex -> gets a path array for leafIndex
         * @param {string} contentType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pathLeafIndexgetsapatharrayforleafIndex: async (contentType: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'contentType' is not null or undefined
            if (contentType === null || contentType === undefined) {
                throw new RequiredError('contentType','Required parameter contentType was null or undefined when calling pathLeafIndexgetsapatharrayforleafIndex.');
            }
            const localVarPath = `/path/2`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (contentType !== undefined && contentType !== null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary /siblingPath/:leafIndex -> gets a siblingPath array for leafIndex
         * @param {string} contentType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        siblingPathLeafIndexgetsasiblingPatharrayforleafIndex: async (contentType: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'contentType' is not null or undefined
            if (contentType === null || contentType === undefined) {
                throw new RequiredError('contentType','Required parameter contentType was null or undefined when calling siblingPathLeafIndexgetsasiblingPatharrayforleafIndex.');
            }
            const localVarPath = `/siblingPath/2`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (contentType !== undefined && contentType !== null) {
                localVarHeaderParameter['Content-Type'] = String(contentType);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * inserts a node object
         * @summary /start -> starts the event filter
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        startstartstheeventfilter: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/start`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary /update -> updates the merkle tree
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateupdatesthemerkletree: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MerkleTreeApi - functional programming interface
 * @export
 */
export const MerkleTreeApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary /path/:leafIndex -> gets a path array for leafIndex
         * @param {string} contentType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pathLeafIndexgetsapatharrayforleafIndex(contentType: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await MerkleTreeApiAxiosParamCreator(configuration).pathLeafIndexgetsapatharrayforleafIndex(contentType, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary /siblingPath/:leafIndex -> gets a siblingPath array for leafIndex
         * @param {string} contentType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async siblingPathLeafIndexgetsasiblingPatharrayforleafIndex(contentType: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await MerkleTreeApiAxiosParamCreator(configuration).siblingPathLeafIndexgetsasiblingPatharrayforleafIndex(contentType, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * inserts a node object
         * @summary /start -> starts the event filter
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async startstartstheeventfilter(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await MerkleTreeApiAxiosParamCreator(configuration).startstartstheeventfilter(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary /update -> updates the merkle tree
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateupdatesthemerkletree(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await MerkleTreeApiAxiosParamCreator(configuration).updateupdatesthemerkletree(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * MerkleTreeApi - factory interface
 * @export
 */
export const MerkleTreeApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary /path/:leafIndex -> gets a path array for leafIndex
         * @param {string} contentType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pathLeafIndexgetsapatharrayforleafIndex(contentType: string, options?: any): AxiosPromise<void> {
            return MerkleTreeApiFp(configuration).pathLeafIndexgetsapatharrayforleafIndex(contentType, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary /siblingPath/:leafIndex -> gets a siblingPath array for leafIndex
         * @param {string} contentType 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        siblingPathLeafIndexgetsasiblingPatharrayforleafIndex(contentType: string, options?: any): AxiosPromise<void> {
            return MerkleTreeApiFp(configuration).siblingPathLeafIndexgetsasiblingPatharrayforleafIndex(contentType, options).then((request) => request(axios, basePath));
        },
        /**
         * inserts a node object
         * @summary /start -> starts the event filter
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        startstartstheeventfilter(options?: any): AxiosPromise<void> {
            return MerkleTreeApiFp(configuration).startstartstheeventfilter(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary /update -> updates the merkle tree
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateupdatesthemerkletree(options?: any): AxiosPromise<void> {
            return MerkleTreeApiFp(configuration).updateupdatesthemerkletree(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MerkleTreeApi - object-oriented interface
 * @export
 * @class MerkleTreeApi
 * @extends {BaseAPI}
 */
export class MerkleTreeApi extends BaseAPI {
    /**
     * 
     * @summary /path/:leafIndex -> gets a path array for leafIndex
     * @param {string} contentType 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MerkleTreeApi
     */
    public pathLeafIndexgetsapatharrayforleafIndex(contentType: string, options?: any) {
        return MerkleTreeApiFp(this.configuration).pathLeafIndexgetsapatharrayforleafIndex(contentType, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary /siblingPath/:leafIndex -> gets a siblingPath array for leafIndex
     * @param {string} contentType 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MerkleTreeApi
     */
    public siblingPathLeafIndexgetsasiblingPatharrayforleafIndex(contentType: string, options?: any) {
        return MerkleTreeApiFp(this.configuration).siblingPathLeafIndexgetsasiblingPatharrayforleafIndex(contentType, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * inserts a node object
     * @summary /start -> starts the event filter
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MerkleTreeApi
     */
    public startstartstheeventfilter(options?: any) {
        return MerkleTreeApiFp(this.configuration).startstartstheeventfilter(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary /update -> updates the merkle tree
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MerkleTreeApi
     */
    public updateupdatesthemerkletree(options?: any) {
        return MerkleTreeApiFp(this.configuration).updateupdatesthemerkletree(options).then((request) => request(this.axios, this.basePath));
    }
}
