/* tslint:disable */
/* eslint-disable */
/**
 * merkle-tree
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MetadatacontractAddressInsertsthecontractaddressofthetreeRequest
 */
export interface MetadatacontractAddressInsertsthecontractaddressofthetreeRequest {
    /**
     * 
     * @type {string}
     * @memberof MetadatacontractAddressInsertsthecontractaddressofthetreeRequest
     */
    contractName: any;
    /**
     * 
     * @type {string}
     * @memberof MetadatacontractAddressInsertsthecontractaddressofthetreeRequest
     */
    contractAddress: any;
}
