/* tslint:disable */
/* eslint-disable */
/**
 * merkle-tree
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface NodenodeIndexUpdatesanodeatnodeIndexfortreeIdRequest
 */
export interface NodenodeIndexUpdatesanodeatnodeIndexfortreeIdRequest {
    /**
     * 
     * @type {string}
     * @memberof NodenodeIndexUpdatesanodeatnodeIndexfortreeIdRequest
     */
    contractName: any;
    /**
     * 
     * @type {string}
     * @memberof NodenodeIndexUpdatesanodeatnodeIndexfortreeIdRequest
     */
    treeId: any;
    /**
     * 
     * @type {Node2}
     * @memberof NodenodeIndexUpdatesanodeatnodeIndexfortreeIdRequest
     */
    node: any;
}
