/* tslint:disable */
/* eslint-disable */
/**
 * merkle-tree
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Node2
 */
export interface Node2 {
    /**
     * 
     * @type {string}
     * @memberof Node2
     */
    value: any;
    /**
     * 
     * @type {number}
     * @memberof Node2
     */
    nodeIndex: any;
}
